import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root"
})
export class StoryService {

  story: Object;

  constructor() {
    this.story = {
      1: {
        // tslint:disable-next-line: max-line-length
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi volutpat mattis vulputate. Vivamus interdum diam sed odio fermentum, sed iaculis lorem varius. Nunc bibendum varius urna, ac luctus est lobortis at. Etiam fermentum sapien quis iaculis venenatis. Sed ut lectus id ipsum gravida tincidunt quis vitae ante. Donec auctor suscipit mauris nec suscipit. Nullam a ultricies orci  Quisque iaculis, leo sed posuere mollis, dui enim vehicula lectus, vitae varius nisi lacus ultricies tellus. Nam sit amet magna sed ante mollis consequat. Maecenas laoreet nulla eu turpis blandit, in lacinia justo tincidunt. In ut nulla metus. Nunc auctor libero vitae ultricies ornare. Integer sodales malesuada eros, facilisis convallis elit tempus sed. Nulla ac laoreet ipsum. Maecenas sit amet iaculis nisi, et pellentesque nisl. Integer quis ipsum dui. Praesent id lectus ultrices, porta lorem eu, laoreet magna. Mauris rutrum leo neque, iaculis facilisis orci sagittis quis. Suspendisse convallis pretium fringilla. Suspendisse rhoncus id nunc eget sollicitudin. Phasellus egestas erat quis est euismod, ut imperdiet risus fermentum. Nunc id auctor elit, at ultricies justo. In sollicitudin velit finibus, iaculis orci at, pulvinar nisi. Nam nec condimentum ipsum, nec vehicula quam. Ut aliquet, metus vel lacinia auctor, erat lorem facilisis elit, a tempus ex risus at nulla. In sit amet porttitor metus, sed scelerisque orci. Quisque ac nunc non tortor lobortis malesuada Vestibulum ut nisl iaculis, congue libero sit amet, vehicula nunc. Nunc a dictum nibh, id consectetur libero. Praesent pretium auctor ligula. Duis odio ante, blandit in vehicula eget, laoreet at ex. Integer euismod felis velit, a scelerisque libero bibendum id. Pellentesque dignissim convallis aliquet. Aenean egestas metus ut dapibus egestas. Fusce ultricies erat metus, vel volutpat sapien tincidunt sed. Fusce elementum varius accumsan. Duis lacinia, ligula vitae commodo finibus, odio urna malesuada est, vitae vestibulum nibh enim in nisi. Cras in congue augue. Nunc faucibus nisl lorem, aliquam semper tellus tempus nec. Sed sit amet ultricies magna. Nulla porttitor diam sed lacus finibus, sed sagittis lacus rhoncus. Nulla facilisi Donec quis porta massa, luctus sollicitudin est. Duis pretium, arcu in commodo tristique, turpis diam molestie nisl, et elementum lorem mauris vitae turpis. Proin eleifend elementum augue dignissim vehicula. Proin euismod aliquet ipsum. Suspendisse enim dui, interdum sit amet orci eget, tincidunt.",
        image: "http:\\google.com",
        choices: [2, 3],
        buttonText: "Home"
      },
      2: {
        // tslint:disable-next-line: max-line-length
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi volutpat mattis vulputate. Vivamus interdum diam sed odio fermentum, sed iaculis lorem varius. Nunc bibendum varius urna, ac luctus est lobortis at. Etiam fermentum sapien quis iaculis venenatis. Sed ut lectus id ipsum gravida tincidunt quis vitae ante. Donec auctor suscipit mauris nec suscipit. Nullam a ultricies orci  Quisque iaculis, leo sed posuere mollis, dui enim vehicula lectus, vitae varius nisi lacus ultricies tellus. Nam sit amet magna sed ante mollis consequat. Maecenas laoreet nulla eu turpis blandit, in lacinia justo tincidunt. In ut nulla metus. Nunc auctor libero vitae ultricies ornare. Integer sodales malesuada eros, facilisis convallis elit tempus sed. Nulla ac laoreet ipsum. Maecenas sit amet iaculis nisi, et pellentesque nisl. Integer quis ipsum dui. Praesent id lectus ultrices, porta lorem eu, laoreet magna. Mauris rutrum leo neque, iaculis facilisis orci sagittis quis. Suspendisse convallis pretium fringilla. Suspendisse rhoncus id nunc eget sollicitudin. Phasellus egestas erat quis est euismod, ut imperdiet risus fermentum. Nunc id auctor elit, at ultricies justo. In sollicitudin velit finibus, iaculis orci at, pulvinar nisi. Nam nec condimentum ipsum, nec vehicula quam. Ut aliquet, metus vel lacinia auctor, erat lorem facilisis elit, a tempus ex risus at nulla. In sit amet porttitor metus, sed scelerisque orci. Quisque ac nunc non tortor lobortis malesuada Vestibulum ut nisl iaculis, congue libero sit amet, vehicula nunc. Nunc a dictum nibh, id consectetur libero. Praesent pretium auctor ligula. Duis odio ante, blandit in vehicula eget, laoreet at ex. Integer euismod felis velit, a scelerisque libero bibendum id. Pellentesque dignissim convallis aliquet. Aenean egestas metus ut dapibus egestas. Fusce ultricies erat metus, vel volutpat sapien tincidunt sed. Fusce elementum varius accumsan. Duis lacinia, ligula vitae commodo finibus, odio urna malesuada est, vitae vestibulum nibh enim in nisi. Cras in congue augue. Nunc faucibus nisl lorem, aliquam semper tellus tempus nec. Sed sit amet ultricies magna. Nulla porttitor diam sed lacus finibus, sed sagittis lacus rhoncus. Nulla facilisi Donec quis porta massa, luctus sollicitudin est. Duis pretium, arcu in commodo tristique, turpis diam molestie nisl, et elementum lorem mauris vitae turpis. Proin eleifend elementum augue.",
        image: "http:\\google.com",
        choices: [1, 3],
        buttonText: "Left"
      },
      3: {
        // tslint:disable-next-line: max-line-length
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi volutpat mattis vulputate. Vivamus interdum diam sed odio fermentum, sed iaculis lorem varius. Nunc bibendum varius urna, ac luctus est lobortis at. Etiam fermentum sapien quis iaculis venenatis. Sed ut lectus id ipsum gravida tincidunt quis vitae ante. Donec auctor suscipit mauris nec suscipit. Nullam a ultricies orci  Quisque iaculis, leo sed posuere mollis, dui enim vehicula lectus, vitae varius nisi lacus ultricies tellus. Nam sit amet magna sed ante mollis consequat. Maecenas laoreet nulla eu turpis blandit, in lacinia justo tincidunt. In ut nulla metus. Nunc auctor libero vitae ultricies ornare. Integer sodales malesuada eros, facilisis convallis elit tempus sed. Nulla ac laoreet ipsum. Maecenas sit amet iaculis nisi, et pellentesque nisl. Integer quis ipsum dui. Praesent id lectus ultrices, porta lorem eu, laoreet magna. Mauris rutrum leo neque, iaculis facilisis orci sagittis quis. Suspendisse convallis pretium fringilla. Suspendisse rhoncus id nunc eget sollicitudin. Phasellus egestas erat quis est euismod, ut imperdiet risus fermentum. Nunc id auctor elit, at ultricies justo. In sollicitudin velit finibus, iaculis orci at, pulvinar nisi. Nam nec condimentum ipsum, nec vehicula quam. Ut aliquet, metus vel lacinia auctor, erat lorem facilisis elit, a tempus ex risus at nulla. In sit amet porttitor metus, sed scelerisque orci. Quisque ac nunc non tortor lobortis malesuada Vestibulum ut nisl iaculis, congue libero sit amet, vehicula nunc. Nunc a dictum nibh, id consectetur libero. Praesent pretium auctor ligula. Duis odio ante, blandit in vehicula eget, laoreet at ex. Integer euismod felis velit, a scelerisque libero bibendum id. Pellentesque dignissim convallis aliquet. Aenean egestas metus ut dapibus egestas. Fusce ultricies erat metus, vel volutpat sapien tincidunt sed. Fusce elementum varius accumsan. Duis lacinia, ligula vitae commodo finibus, odio urna malesuada est, vitae vestibulum nibh enim in nisi. Cras in congue augue. Nunc faucibus nisl lorem, aliquam semper tellus tempus nec. Sed sit amet ultricies magna. Nulla porttitor diam sed lacus finibus, sed sagittis lacus rhoncus. Nulla facilisi Donec quis porta massa, luctus sollicitudin est. Duis pretium, arcu in commodo tristique, turpis diam molestie nisl, et elementum lorem mauris vitae turpis. Proin eleifend elementum augue dignissim vehicula. Proin euismod .",
        image: "http:\\google.com",
        choices: [1, 2],
        buttonText: "Right"
      }
    };
  }
}
